hpcc-systems/Spark-HPCC

- DataAccess/pom.xml
- Corresponds to HPCC-Platform 7.0.0Beta
> Spark-HPCC 7.0.0-snapshot

- DataAccess/src/main/java/org/hpccsystems/spark/thor/PlainConnection.java
- Defines stream read command value
- Inserts stream reaad command on all requests
- Reads 4 byte status
- Outputs status error value in hex format
- Utilizes static HPCC charset value
> HPCC-19284 Implement new dafileserv protocol

- DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java
- DataAccess/src/main/java/org/hpccsystems/spark/HpccPart.java
- DataAccess/src/main/java/org/hpccsystems/spark/HpccRemoteFileReader.java
- DataAccess/src/main/java/org/hpccsystems/spark/thor/DataPartition.java
- DataAccess/src/test/java/org/hpccsystems/spark/HpccFileTest.java
- DataAccess/src/test/java/org/hpccsystems/spark/RecordTest.java
Extended HpccPart to accept an array of DataPartitions, each DataPartition mapped to a singler THOR file pert.
Extended HpccRemoteFileReader to work with an array of DataPartitions.
Extended test code for multiple data partitions.
Signed-off-by: johnholt <john.d.holt@lexisnexisrisk.com>
> HPCC-19604 Spark access to super files

- DataAccess/src/main/java/org/hpccsystems/spark/Content.java
- Adds field name to data converting error message
> HPCC-20108 Improve error message

- DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java
- Removes restriction due to change in ESP HPCC-20071
> HPCC-20039 Remove multi-subfile restriction on superfiles

- DataAccess/pom.xml
- DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java
- DataAccess/src/main/java/org/hpccsystems/spark/HpccPart.java
- DataAccess/src/main/java/org/hpccsystems/spark/thor/DataPartition.java
- DataAccess/src/main/java/org/hpccsystems/spark/thor/PlainConnection.java
- DataAccess/src/test/java/org/hpccsystems/spark/RecordTest.java
- Acquires file access artifact as part of file stream process
- Changes dafileserv request to new secure format
> HPCC-19203 Utilize DAFILESRV file access mechanism

- DataAccess/pom.xml
> SPARK-HPCC 7.0.0 Branch

- DataAccess/pom.xml
> SPARK-HPCC Update pom to 7.0.0-rc2

- DataAccess/src/main/java/org/hpccsystems/spark/thor/BinaryRecordReader.java
- Modified BinaryRecordReader to not create the additional Row
> HPCC-20582 BinaryRecordReader creates an additional enclosing Row

- DataAccess/src/main/java/org/hpccsystems/spark/thor/PlainConnection.java
- Chooses to perform ssl based connection based on info from ESP
> HPCC-19200 Add Data stream SSL support

- DataAccess/src/main/java/org/hpccsystems/spark/HpccRDD.java
- DataAccess/src/main/java/org/hpccsystems/spark/thor/BinaryRecordReader.java
- DataAccess/src/main/java/org/hpccsystems/spark/thor/DataPartition.java
- DataAccess/src/main/java/org/hpccsystems/spark/thor/PlainConnection.java
- DataAccess/src/test/java/org/hpccsystems/spark/HpccFileTest.java
- Changed PlainConnection to allow buffer reuse
- Added performance settings to the socket
- Added preferred partition locations to RDD
> HPCC-20166 Spark-HPCC Poor I/O performance

- DataAccess/pom.xml
> Spark-HPCC Pom change to 7.0.0-rc3

- DataAccess/src/main/java/org/hpccsystems/spark/ColumnPruner.java
- DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java
- DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
- DataAccess/src/main/java/org/hpccsystems/spark/thor/ClusterRemapper.java
- DataAccess/src/test/java/org/hpccsystems/spark/DataframeTest.java
- DataAccess/src/test/java/org/hpccsystems/spark/HpccFileTest.java
- DataAccess/src/test/java/org/hpccsystems/spark/RDDTest.java
- DataAccess/src/test/java/org/hpccsystems/spark/RecordTest.java
- Removes confusing constructors
- Provides Connection based constructors
- Adds setter methods
- Restructures and cleans up tests mains
> HPCC-20858 Clean up of HPCCFile interface

- DataAccess/pom.xml
> Pom version update 7.0.2

- DataAccess/src/test/java/org/hpccsystems/spark/HpccFileTest.java
- Examples/src/main/scala/org/hpccsystesm/spark_examples/Dataframe_Iris_LR.scala
- Examples/src/main/scala/org/hpccsystesm/spark_examples/Iris_LR.scala
- Updates sample scala code to use latest hpccfile ctr
- Removes invalid test case logic
> Hpcc 20916 Update SparkHpcc test/sample code

- DataAccess/pom.xml
- Changes the casing on the SNAPSHOT version postfix
> HPCC-21064 Uppercase the SNAPSHOT postfix

- DataAccess/pom.xml
> SPARK-HPCC 7.0.6 pom changes

- DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java
- Ensures hpccfile fetches recdef and fileparts info
> HPCC-21254 Ensure HPCCFile creates RecDef and FileParts

- DataAccess/pom.xml
- Updates version to 7.2
Signed-off-by: Pastrana <PastraRX@RISK.REGN.NET>
> HPCC-21681 7.2 version update

- DataAccess/pom.xml
> Pom Version Change: spark-hpcc-7.2.0.1

- DataAccess/pom.xml
> HPCC-21969: Spark pom version update to 7.2.6 and its dependancies

- DataAccess/pom.xml
- Updates project version and dependancies
> HPCC-22019 Update spark-hpcc pom version to 7.2.8

- DataAccess/pom.xml
> HPCC-22151 Update Spark pom version and dependencies

- DataAccess/pom.xml
> SPARK-HPCC split branch 7.2.14

- DataAccess/pom.xml
> HPCC-22333 Update Master pom to 7.4.0-SNAPSHOT

- DataAccess/src/main/java/org/hpccsystems/spark/FileFilterConverter.java
- DataAccess/src/test/java/org/hpccsystems/spark/FileFilterTests.java
> HPCC-22238 Spark Filter Converter

- DataAccess/pom.xml
> SPARK-HPCC 7.2.20 Gold pom update

- DataAccess/pom.xml
> SPARK-HPCC 7.2.22 branch pom update

- DataAccess/pom.xml
> Pom Update: 7.2.22 gold

- DataAccess/pom.xml
> SPARK-HPCC Branch 7.4.0 Gold

- DataAccess/pom.xml
> SPARK-HPCC 7.2.24 Gold Branch

- DataAccess/pom.xml
- DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
- DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccRelationProvider.java
> HPCC-22753 Handle 7.6 espexceptions correctly

- DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccRelationProvider.java
> HPCC-22846 Addresses build break due to extended exception handling

- DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
- DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccRelationProvider.java
> HPCC-22886 HpccFileWriter should provide DFUFileType

- DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccOptions.java
- DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccRelation.java
@rpastrana changes to add in filter support for DataSource API. Still working on adding tests for DataSource & Filters
> JAPI-226 Add mechanism for specifying server side filter to API v1/2 interface

- Examples/pom.xml
> JAPI-243 Update spark-core_2.10 to 2.2.2

- DataAccess/src/main/java/org/hpccsystems/spark/HpccRDD.java
> JAPI-263 HpccRDD constructor should use projected rec def

- DataAccess/src/test/java/org/hpccsystems/spark/InteractiveRDDTest.java
- DataAccess/src/test/java/org/hpccsystems/spark/RDDTest.java
- DataAccess/src/test/java/org/hpccsystems/spark/RemoteTests.java
- Adds remotetest class
- Creates RDD based test casds extending remotetests
> JAPI-235 Create HPCCRDD based JUnit test cases

- DataAccess/pom.xml
- DataAccess/src/main/java/org/hpccsystems/spark/FileFilterConverter.java
- DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
- DataAccess/src/main/java/org/hpccsystems/spark/HpccRDD.java
- DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccRelation.java
- DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccRelationProvider.java
> JAPI-269: Address potential log4j security issue

- DataAccess/pom.xml
> JAPI-275 Spark parse_pom.sh script inclusion

- DataAccess/pom.xml
> Spark-Jenkins profile fix and default junit tests set

- DataAccess/pom.xml
- Added missing dep from Pyrolite 5
> JAPI-310 Spark connector: Missing pickler dependancy

- DataAccess/pom.xml
> JAPI-305 Automate non-snapshot release process on sonatype

- DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java
- DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
- DataAccess/src/main/java/org/hpccsystems/spark/HpccRDD.java
- DataAccess/src/main/java/org/hpccsystems/spark/SparkSchemaTranslator.java
- DataAccess/src/main/java/org/hpccsystems/spark/package-info.java
> hpcc4j-312 Manually fix javadoc errors and warnings

- DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccRelation.java
- DataAccess/src/test/java/org/hpccsystems/spark/HpccRelationTest.java
- Reports handled filters
- Integrates Spark filter in buidscan
> HPCC4J-384 Support pushdown-filtering

- DataAccess/src/test/java/org/hpccsystems/spark/HpccRelationTest.java
> HPCC4J-388 Remove unused spark connection logic in junit

- DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccOptions.java
- DataAccess/src/test/java/org/hpccsystems/spark/HpccRelationTest.java
- DataAccess/src/test/java/org/hpccsystems/spark/RDDTest.java
> JAPI-397 Enable Spark remote test

- DataAccess/pom.xml
- DataAccess/src/main/java/org/hpccsystems/spark/datasource/package-info.java
- DataAccess/src/main/java/org/hpccsystems/spark/package-info.java
- DataAccess/src/main/javadoc/overview.html
> HPCC4J-403 Provides proper Javadoc coverage

- .github/workflows/javadocTest.yml
> Adding javadoc test github action

- DataAccess/pom.xml
- DataAccess/src/main/java/org/hpccsystems/spark/FileFilterConverter.java
- DataAccess/src/main/java/org/hpccsystems/spark/GenericRowRecordAccessor.java
- DataAccess/src/main/java/org/hpccsystems/spark/GenericRowRecordBuilder.java
- DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
- DataAccess/src/main/java/org/hpccsystems/spark/HpccRDD.java
- DataAccess/src/main/java/org/hpccsystems/spark/SparkSchemaTranslator.java
- DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccOptions.java
- DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccRelation.java
- DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccRelationProvider.java
> JAPI-407 Add JavaDoc descriptions to classes to Spark-HPCC

- DataAccess/pom.xml
> JAPI-411 Spark no encoded chars in pom

- DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccRelation.java
> JAPI-420 HpccRelation should declare an equals function

- DataAccess/pom.xml
> HPCC4J-444 Attempted fix for intermittent spark-hpcc package deployment failure

- .github/workflows/spark-hpcc-remote-test.yml
- DataAccess/pom.xml
- Created a spark34 profile in pom
- Added spark34 profile to github action
> HPCC4j-526 Added Spark 3.4+ to test matrix

- .github/workflows/publish-release-on-merge.yml
- Added a new github action workflow to publish builds on release tag
> HPCC4J-501 Deploy artifacts via github action

- .github/workflows/publish-snapshots-on-merge.yml
> JAPI-501 Disable snapshot publish on release tag

- .github/workflows/publish-release-on-merge.yml
- .github/workflows/publish-snapshots-on-merge.yml
- .github/workflows/spark-hpcc-remote-test.yml
- Added retry logic to allow for deployment delay of deps.
- Disabled tests during deployment build step
> JAPI-501 Build and deploy via Github Actions

- .github/workflows/publish-release-on-merge.yml
- Corrected script to set signing secret correctly
> HPCC4J-566 Spark-HPCC Deploy script signing failure

- DataAccess/pom.xml
- Added changes missed during upmerge process
> HPCC4J-566 Deploy script failure

- .github/workflows/Jirabot.yml
- .github/workflows/JirabotMerge.yml
- Added jirabot / jirabot merge
> HPCC4J-627 Add Jirabot / Jirabot Merge

- DataAccess/src/main/java/org/hpccsystems/spark/SparkSchemaTranslator.java
- Mapped filepos to Long type in Spark
> HPCC4J-653 Spark-HPCC: Schema translation map filepos to integer

- DataAccess/pom.xml
- Added overrides for outdated dependencies
> HPCC4J-662 Upgrade out of date Spark dependencies

- .github/workflows/JirabotMerge.yml
- .github/workflows/Nightly.yml
- .github/workflows/javadocTest.yml
- .github/workflows/publish-release-on-merge.yml
- .github/workflows/spark-hpcc-remote-test.yml
HPCC4J-666 Update github actions plugin versions
> HPCC4J-666 Update github actions plugin versions
