hpcc-systems/Spark-HPCC

Examples/src/main/scala/org/hpccsystesm/spark_examples/Dataframe_Iris_LR.scala
Example in Scala using the Dataframe support.  This example runs the ML version (not MLLib) of Logistic Regression on the Iris dataset.
Signed-off-by: johnholt <john.d.holt@lexisnexisrisk.com>
=> HPCC-19321 Dataframe example

DataAccess/pom.xml
- Sets java level to 1.8 for project
- Declares wsclient dep
- Allows SNAPSHOT dep (should revert once wsclient 2.0.0 is gold)
=> #Spark-HPCC-3 Set java level and wsclient dep

DataAccess/src/main/java/org/hpccsystems/spark/FilePart.java, DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/PlainConnection.java
HpccFile changed to get compressed flag from the DFUFileDetail and pass on to FilePart constructor.
FilePart changed to carry compressed flag and to change file parts place holder to number of parts (HPCC-19619).
PlainConnection changed to process error message strings without length prefix; and to add compredded flag to json request string.
Signed-off-by: johnholt <john.d.holt@lexisnexisrisk.com>
=> HPCC-19611 Compressed file read

DataAccess/src/main/java/org/hpccsystems/spark/ColumnPruner.java, DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java, DataAccess/src/main/java/org/hpccsystems/spark/RecordDef.java, DataAccess/src/main/java/org/hpccsystems/spark/TargetColumn.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/DefEntry.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/DefEntryField.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/DefEntryRoot.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/DefEntryType.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/DefToken.java, DataAccess/src/test/java/org/hpccsystems/spark/DataframeTest.java, DataAccess/src/test/java/org/hpccsystems/spark/HpccFileTest.java, DataAccess/src/test/java/org/hpccsystems/spark/PruneTest.java, DataAccess/src/test/java/org/hpccsystems/spark/RDDTest.java, DataAccess/src/test/java/org/hpccsystems/spark/RecordTest.java
Changed HpccFile to accept a field list string as a selection parameter.  List is comma separated with compound names in normal dot notation.  Changed RecordDef to have the original JSON data definition changed.  Changed the DefToken to convert back to string format.
Added ColumnPruner, TargetColumn, and DefEntry et.al. to implement pruning fields and types from the output definition.
Updated test programs to solicit a field selection string.  Simplified RDDTest to only show data on console.
Signed-off-by: johnholt <john.d.holt@lexisnexisrisk.com>
=> HPCC-19201 Support field selection to prune unwanted data

DataAccess/src/main/java/org/hpccsystems/spark/ColumnPruner.java, DataAccess/src/main/java/org/hpccsystems/spark/HpccDataframeFactory.java, DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java, DataAccess/src/main/java/org/hpccsystems/spark/HpccPart.java, DataAccess/src/main/java/org/hpccsystems/spark/HpccRDD.java, DataAccess/src/main/java/org/hpccsystems/spark/HpccRemoteFileReader.java, DataAccess/src/main/java/org/hpccsystems/spark/package-info.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/AddrRemapper.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/BinaryRecordReader.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/ClusterRemapper.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/DataPartition.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/DefEntry.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/DefEntryField.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/DefEntryRoot.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/DefEntryType.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/DefToken.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/FieldFilter.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/FieldFilterRange.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/FileFilter.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/HpccAccessException.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/PlainConnection.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/RemapInfo.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/TypeDef.java, DataAccess/src/test/java/org/hpccsystems/spark/DataframeTest.java, DataAccess/src/test/java/org/hpccsystems/spark/HpccFileTest.java, DataAccess/src/test/java/org/hpccsystems/spark/RDDTest.java, DataAccess/src/test/java/org/hpccsystems/spark/RecordTest.java
Reads index datasets with filtering.  Increased the number of datatypes supported and suppressed datatypes that should not be supported.  Indexes have an additional file part, so the relationship between Spark partitions and file parts was made indirect.
ColumnPruner was enhanced to suppress datatypes that are unsupported and to change the output format of particular types (like QSTRING) into a more standard type.  The enhancement eliminated shortcut processing through the ColumnPruner.
HpccDataFrameFactory was modified to use the replacement of FilePart with HpccPart.
HpccFile was enhanced by adding several convenience constructors and by adding the display of the JSON layout definition in the event of a problem processing the definition.  The FilePart object was refactored into an …
=> HPCC-19375 Index pull into Spark environment

DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java
- Register / use builtin Python picklers with GenericRowWithSchema
- Implemented a getRDD version that allows PySpark to create RDDs
=> HPCC-19369 Pyrolite serialization and de-serialization

DataAccess/src/main/java/org/hpccsystems/spark/thor/PlainConnection.java
- Added replyLimit parameter to read requests
- Determined 4MB requests to be optimal based on benchmarking
=> SPAR-7 Set response size on read requests

DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/PlainConnection.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/RFCCodes.java
- Creates RFCCodes class with all known dafilesrv codes
- Handles 2 file access expiry error codes
- Allows developers to overwrite default expiry
=> HPCC-20580 Track DAFILESERV trx codes

DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/BinaryRecordWriter.java, DataAccess/src/main/java/org/hpccsystems/spark/thor/SparkField.java
=> HPCC-19204 Spark-HPCC class(es) to store data on an RDD and a Dataframe to THOR

DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
- Corrected repartitioning code
=> HPCC-21706 Re-partitioning fails when writing to HPCC from Spark

DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java, DataAccess/src/main/java/org/hpccsystems/spark/HpccRDD.java
- Registered python picklers during RDD iteration
- Added in a task completion listener to close the HPCCRemoteFileReader in a timely manner
- Added in JavaRDD versions of saveToHPCC to make Python code cleaner
=> HPCC-21714 Python Picklers not registered on Spark worker nodes

DataAccess/pom.xml, DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java, DataAccess/src/main/java/org/hpccsystems/spark/HpccRDD.java, DataAccess/src/main/java/org/hpccsystems/spark/RowConstructor.java
- Added custom Unpickler constructor for PySpark Rows
- Created an inferSchema method to generate a valid Java Spark Schema
- Added a new saveToHPCC that allows the user to specify the Spark Schema instead of using the Schema from the RDD rows
=> HPCC-21797 Add missing PySpark to Spark Row & Schema conversion functions

DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java, DataAccess/src/main/java/org/hpccsystems/spark/PySparkField.java, DataAccess/src/main/java/org/hpccsystems/spark/PySparkFieldConstructor.java
- Modified inferSchema to maintain field order
=> HPCC-21797 Add missing PySpark to Spark Row & Schema conversion function

DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java, DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java, DataAccess/src/main/java/org/hpccsystems/spark/HpccRDD.java
- Corrected issue in HpccRDD where the projected record definition was supplied to HpccRemoteFileReader instead of the original record definition.
=> Spark-HPCC: Null exception when using column pruning

DataAccess/pom.xml
- Updating to anything newer than 2.4.1 caused build/junit time issues
-- IOException when zipping org/xerial/snappy/BitShuffle.class: invalid LOC header
=> HPCC-22509 Update to spark-core 2.4.1

DataAccess/README.md, DataAccess/pom.xml, DataAccess/src/main/java/org/hpccsystems/spark/HpccRDD.java, README.md
- Labels spark library dependancies as provided
- Updates spark lib dep to 2.4.6
- Removes spark ml deps
- Updates readmes
=> HPCC4J-400 Update spark library dependancies

DataAccess/pom.xml
Bumps log4j-core from 2.13.2 to 2.15.0.
---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-core
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
=> Bump log4j-core from 2.13.2 to 2.15.0 in /DataAccess

DataAccess/pom.xml
Bumps log4j-core from 2.15.0 to 2.16.0.
---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-core
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
=> Bump log4j-core from 2.15.0 to 2.16.0 in /DataAccess

DataAccess/pom.xml
Bumps log4j-core from 2.16.0 to 2.17.0.
---
updated-dependencies:
- dependency-name: org.apache.logging.log4j:log4j-core
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
=> Bump log4j-core from 2.16.0 to 2.17.0 in /DataAccess

.github/workflows/Nightly.yml, .github/workflows/SparkConnectorPRBuild.yml, .github/workflows/javadocTest.yml, .github/workflows/sparkRemoteUnitTests.yml, .github/workflows/sparkconnectorbuildonmerge.yml, DataAccess/pom.xml
- Updated POM file to use release configuration
- Updated Github actions to use JDK 11 required by release build feature
=> HPCC4J-523 Incorrect Java version linking based on JDK

DataAccess/pom.xml
- Updated POM release profiles to skip integration tests
=> HPCC4J-527 Spark-HPCC: Maven deploy shouldn't run integration tests

DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccOptions.java, DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccRelation.java, DataAccess/src/test/java/org/hpccsystems/spark/HpccRelationIntegrationTest.java, Examples/PySparkExample.ipynb, README.md
- Exposed UseTLK option to Spark-HPCC connector
- Added example and description of use to Examples PySpark document
- Added a test case for options pass through
=> HPCC4J-615 Expose the UseTLK option from DFSClient

DataAccess/src/main/java/org/hpccsystems/spark/datasource/HpccOptions.java, Examples/PySparkExample.ipynb
- Allowed path used in Datasource API to formatted as URIs to fix Databricks issue
=> HPCC4J-625 SparkHPCC: Path support Databricks URI requirements
